### ISSUE TITLE
Happy Birthday!

### ISSUE THREAD

**Issue by brianburridge** [ejmellish/Homework#6]
_This assignment is due on Jan 28, 2015._
- Create a Ruby script to ask the user for their name and then wish them a Happy Birthday by name
- Add some comments to your code
- Put this code in a gist and paste the link from the gist in a comment of this issue
## Bonus
- Add another prompt for birthdate
- Show the birth date in parenthesis after the greeting
- Note: user must enter date in like: 2014/09/22 or 2014-09-22
- Change the output formatting to: Friday, April 1, 1974
- Capitalize the user's name

**Comment by ejmellish** [comment]
https://gist.github.com/ejmellish/a627dda385d9e4a1a403

**Comment by ejmellish** [comment]
#bonus ask for birthdate
print "Great, now please enter your birthday"
require 'date'
Date = gets.chomp
Date.strptime('%Y-%m-%d')
puts "#{date}"

this was the final attempt at the bonus, which failed :(

**Comment by ejmellish** [comment]
https://gist.github.com/ejmellish/e3d270f354555a759ee8

Thanks Brian! We hashed it out pretty thoroughly after you left. I now have a much more clear understanding of converting strings into objects before running functions (like date.parse) on it

**Comment by brianburridge** [comment]
@ejmellish Keep in mind, Strings are objects too. In this exercise you were converting from String -> Date -> String.
:+1:
