### ISSUE TITLE
Creating Variables and Literals

### ISSUE THREAD

**Issue by brianburridge** [ejmellish/Homework#7]
_This assignment is due on Jan 28, 2015._
- Create code for each comment in [this gist](https://gist.github.com/brianburridge/79de494772daf7976ea9)
- Run the code and paste the output into your issue as a comment for this assignment
- It should list all the proper class names and all class tests should result in 'true'
- Before you run it, can you guess what will happen with the constant code you've created?

**Comment by ejmellish** [comment]
https://gist.github.com/ejmellish/993796cde6e3520cb34d

**Comment by ejmellish** [comment]
String
String
Fixnum
Array
Array
Hash
true
false
true
true
true
true
String
Fixnum
Array
Array
Symbol
ass7.rb:58: warning: already initialized constant TEACHER
ass7.rb:55: warning: previous definition of TEACHER was here
TEACHER
Ethan-Mellishs-MacBook-Pro:ethan ethanmellish$

**Comment by brianburridge** [comment]
@ejmellish I can't see the code for this. Can you place that in a gist for me? Also, the final output is the constants name, TEACHER, but not the value. I believe there is at least two other problems too, but I can't see your code.

**Comment by ejmellish** [comment]
https://gist.github.com/ejmellish/2877938b7be331328c18

**Comment by ejmellish** [comment]
ethanmelishsmbp:ethan ethanmellish$ ruby ass7.rb
String
Date
Fixnum
Array
Array
Hash
true
true
true
true
true
true
String
Fixnum
Array
Hash
Symbol
ass7.rb:58: warning: already initialized constant TEACHER
ass7.rb:55: warning: previous definition of TEACHER was here
TORREY

**Comment by brianburridge** [comment]
:+1:
